---
language: generic
sudo: required
services:
  - docker
env:
  global:
    - DOCKER_VERSION=1.10.2-0~trusty
    - DOCKER_COMPOSE_VERSION=1.6.2
  matrix:
    - OS=jessie64 PROCESS_CONTROL=systemd
    - OS=jessie64 PROCESS_CONTROL=supervisor
    - OS=trusty64 PROCESS_CONTROL=supervisor
    - OS=centos7  PROCESS_CONTROL=systemd
before_install:
  - sudo -E ./scripts/install-docker.sh
install: true
script:
  - make "${OS}" test
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
