---
- name: check for supported OS
  assert:
    that:
      - "ansible_os_family in supported_ansible_os_families"

- name: include OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: include Debian-specific tasks
  include: Debian.yml
  when: ansible_os_family == 'Debian'

- name: include Red Hat-specific tasks
  include: RedHat.yml
  when: ansible_os_family == 'RedHat'

- name: create Minecraft group
  group:
    state=present
    name={{ minecraft_group }}
    system=yes

- name: create Minecraft user
  user:
    state=present
    name={{ minecraft_user }}
    group={{ minecraft_group }}
    home={{ minecraft_home }}

- include: supervisor.yml
  when: minecraft_process_control == 'supervisor'

- include: systemd.yml
  when: minecraft_process_control == 'systemd'

- name: download Minecraft server
  get_url:
    url={{ minecraft_url }}/{{ minecraft_version }}/minecraft_server.{{ minecraft_version }}.jar
    dest={{ minecraft_home }}/minecraft_server.{{ minecraft_version }}.jar
    owner={{ minecraft_user }}
    group={{ minecraft_group }}
    mode=0755

- name: symlink Minecraft server
  file:
    src={{ minecraft_home }}/minecraft_server.{{ minecraft_version }}.jar
    path={{ minecraft_home }}/minecraft_server.jar
    owner={{ minecraft_user }}
    group={{ minecraft_group }}
    state=link
  notify:
    - restart Minecraft

- name: agree to EULA
  copy:
    src=eula.txt
    dest={{ minecraft_home }}/eula.txt
    mode=0644
    owner={{ minecraft_user }}
    group={{ minecraft_group }}
  notify:
    - enable service

- include: acl.yml
    list=whitelist
    data={{ minecraft_whitelist }}
  when: "minecraft_whitelist"

- include: acl.yml
    list=ops
    data={{ minecraft_ops }}
  when: "minecraft_ops"

- include: acl.yml
    list=banned-players
    data={{ minecraft_banned_players }}
  when: "minecraft_banned_players"

- include: acl.yml
    list=banned-ips
    data={{ minecraft_banned_ips }}
  when: "minecraft_banned_ips"
