---
- name: install units
  template:
    src={{ item }}.j2
    dest=/etc/systemd/system/{{ item }}
    owner=root
    group=root
    mode=0644
  with_items:
    - minecraft.service
    - minecraft.socket

- name: reload systemd
  command: systemctl daemon-reload
  sudo: true

- name: configure console directory
  template:
    src=tmpfiles.d/minecraft.conf.j2
    dest=/etc/tmpfiles.d/minecraft.conf
    owner=root
    group=root
    mode=0644

- name: create console directory
  command: systemd-tmpfiles --create /etc/tmpfiles.d/minecraft.conf
  sudo: true
